// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWay2021.Server.Data;

namespace MyWay2021.Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210219110122_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "2301D884-221A-4E7D-B509-0113DCC043E1",
                            ConcurrencyStamp = "2f048e5a-df75-45af-9fcf-3b18e763b179",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "7D9B7113-A8F8-4035-99A7-A20DD400F6A3",
                            ConcurrencyStamp = "9c16fb56-bfe4-4034-abf7-024d14a57de7",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Utilizador",
                            NormalizedName = "UTILIZADOR"
                        },
                        new
                        {
                            Id = "78A7570F-3CE5-48BA-9461-80283ED1D94D",
                            ConcurrencyStamp = "84eefa69-7fcb-42aa-8b89-e4b255fcbcfb",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consultor",
                            NormalizedName = "CONSULTOR"
                        });
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "B22698B8-42A2-4115-9631-1C2D1E2AC5F7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "064f9b20-cb50-4cf5-b741-f0b6610d943a",
                            Email = "rui.santos@portway.pt",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nome = "Rui Pereira",
                            NormalizedEmail = "RUI.SANTOS@PORTWAY.PT",
                            NormalizedUserName = "RAPEREIRA",
                            PasswordHash = "AQAAAAEAACcQAAAAEIHumMYXfgLiAHQ5MQkg0YxWfvo0/TvKEF9j/G0Z/KGgWjg8klsmyIBjm/vcnfmTQw==",
                            PhoneNumber = "XXXXXXXXXXXXX",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            TwoFactorEnabled = false,
                            UserName = "rapereira"
                        });
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.AppUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "B22698B8-42A2-4115-9631-1C2D1E2AC5F7",
                            RoleId = "2301D884-221A-4E7D-B509-0113DCC043E1"
                        });
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.UserUh", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UhID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "UhID");

                    b.HasIndex("UhID");

                    b.HasIndex("UserId1");

                    b.ToTable("UsersUhs");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b22698b8-42a2-4115-9631-1c2d1e2ac5f7"),
                            UhID = new Guid("807aeb52-f2d7-4152-8410-a668604a41d4")
                        },
                        new
                        {
                            UserId = new Guid("b22698b8-42a2-4115-9631-1c2d1e2ac5f7"),
                            UhID = new Guid("7a525467-1367-4ddf-9802-6bc44ae695ac")
                        },
                        new
                        {
                            UserId = new Guid("b22698b8-42a2-4115-9631-1c2d1e2ac5f7"),
                            UhID = new Guid("7b277149-86d7-4c19-816c-0e97e803f491")
                        },
                        new
                        {
                            UserId = new Guid("b22698b8-42a2-4115-9631-1c2d1e2ac5f7"),
                            UhID = new Guid("7f6e20bd-7106-4c6f-a23d-dde9b0a1e471")
                        });
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.Equipamento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ambulift")
                        .HasColumnType("int");

                    b.Property<int>("AmbuliftOp")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatorioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VeiculoEletrico")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoEletricoOp")
                        .HasColumnType("int");

                    b.Property<int>("Vta")
                        .HasColumnType("int");

                    b.Property<int>("VtaOp")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RelatorioID");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.Incumprimento", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aceites")
                        .HasColumnType("int");

                    b.Property<int>("AceitesMais15")
                        .HasColumnType("int");

                    b.Property<int>("AceitesMenos15")
                        .HasColumnType("int");

                    b.Property<int>("Imputados")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatorioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Respondidos")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RelatorioID");

                    b.ToTable("Incumprimentos");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.RelatorioDiario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumChegadas")
                        .HasColumnType("int");

                    b.Property<int>("NumPartidas")
                        .HasColumnType("int");

                    b.Property<Guid>("UhID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UhID");

                    b.ToTable("RelatoriosDiarios");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.Sla", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChegadaCpnMais10Menos20")
                        .HasColumnType("int");

                    b.Property<int>("ChegadaCpnMais20")
                        .HasColumnType("int");

                    b.Property<int>("ChegadaCpnMais5Menos10")
                        .HasColumnType("int");

                    b.Property<int>("ChegadaCpnMenos5")
                        .HasColumnType("int");

                    b.Property<int>("ChegadaSpnMais15Menos20")
                        .HasColumnType("int");

                    b.Property<int>("ChegadaSpnMais20Menos30")
                        .HasColumnType("int");

                    b.Property<int>("ChegadaSpnMais30")
                        .HasColumnType("int");

                    b.Property<int>("ChegadaSpnMenos15")
                        .HasColumnType("int");

                    b.Property<int>("Menos90MinMais25Menos35")
                        .HasColumnType("int");

                    b.Property<int>("Menos90MinMais35Menos45")
                        .HasColumnType("int");

                    b.Property<int>("Menos90MinMais45")
                        .HasColumnType("int");

                    b.Property<int>("Menos90MinMenos25")
                        .HasColumnType("int");

                    b.Property<int>("PartidaCpnMais10Menos20")
                        .HasColumnType("int");

                    b.Property<int>("PartidaCpnMais20Menos30")
                        .HasColumnType("int");

                    b.Property<int>("PartidaCpnMais30")
                        .HasColumnType("int");

                    b.Property<int>("PartidaCpnMenos10")
                        .HasColumnType("int");

                    b.Property<int>("PartidaSpnMais25Menos35")
                        .HasColumnType("int");

                    b.Property<int>("PartidaSpnMais35Menos45")
                        .HasColumnType("int");

                    b.Property<int>("PartidaSpnMais45")
                        .HasColumnType("int");

                    b.Property<int>("PartidaSpnMenos25")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatorioID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("RelatorioID");

                    b.ToTable("Slas");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.StaffOnDuty", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Escalado")
                        .HasColumnType("int");

                    b.Property<Guid>("FuncaoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Limitacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Manha")
                        .HasColumnType("int");

                    b.Property<int>("Noite")
                        .HasColumnType("int");

                    b.Property<int>("Pnt")
                        .HasColumnType("int");

                    b.Property<Guid>("RelatorioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tarde")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FuncaoID");

                    b.HasIndex("RelatorioID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.TrabalhoSuplementar", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DC")
                        .HasColumnType("float");

                    b.Property<double>("DS")
                        .HasColumnType("float");

                    b.Property<Guid>("FuncaoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pnt")
                        .HasColumnType("int");

                    b.Property<double>("PrimeiraHora")
                        .HasColumnType("float");

                    b.Property<Guid>("RelatorioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("SegundaHora")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("FuncaoID");

                    b.HasIndex("RelatorioID");

                    b.ToTable("HorasExtra");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.Formando", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FuncaoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("UhID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("FuncaoID");

                    b.HasIndex("UhID");

                    b.ToTable("Formandos");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.Funcao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("ID");

                    b.ToTable("Funcoes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("32d5f978-8841-4f41-9876-9d3bbc0d42ea"),
                            Nome = "COORDENADOR"
                        },
                        new
                        {
                            ID = new Guid("d0704bcc-0316-438e-9c83-408bc3130754"),
                            Nome = "SUB. COORDENADOR"
                        },
                        new
                        {
                            ID = new Guid("1cd22050-9302-46f8-bab3-a92963ea7086"),
                            Nome = "ADMINISTRATIVO"
                        },
                        new
                        {
                            ID = new Guid("7978ce01-a193-47c8-993f-22ca803475da"),
                            Nome = "SUPERVISOR"
                        },
                        new
                        {
                            ID = new Guid("bae2d2f8-ca3a-4864-bce9-c50c784556dd"),
                            Nome = "ALOCADOR"
                        },
                        new
                        {
                            ID = new Guid("1400f058-b85c-47aa-96f8-bccab867d930"),
                            Nome = "ASSISTENTE"
                        },
                        new
                        {
                            ID = new Guid("cf120207-b910-4c05-926d-1d7aea125b81"),
                            Nome = "MOTORISTA"
                        },
                        new
                        {
                            ID = new Guid("3bf6fda6-ff6c-4dfc-9b03-22fd59419ba6"),
                            Nome = "MOTORISTA (AMBULIFT)"
                        });
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.Justificacao", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Justificacoes");

                    b.HasData(
                        new
                        {
                            ID = new Guid("72c36203-f875-44e1-8536-c55b0c8980f5"),
                            Nome = "ATRASO"
                        },
                        new
                        {
                            ID = new Guid("0267e756-9520-4c13-8ff9-33c2232605f9"),
                            Nome = "ACIDENTE DE TRABALHO"
                        },
                        new
                        {
                            ID = new Guid("77f61289-8ea8-4862-bc5d-b19093636140"),
                            Nome = "INCUMPRIMENTO NOTIFICADA"
                        },
                        new
                        {
                            ID = new Guid("b8884316-1b76-4fcc-a217-d4f855254837"),
                            Nome = "INCUMPRIMENTO NÃO NOTIFICADA"
                        });
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.TipoAssistencia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ID");

                    b.ToTable("TiposAssistencia");

                    b.HasData(
                        new
                        {
                            ID = new Guid("1b0cae90-9b19-49c4-9ddf-51d8d5577cc6"),
                            Tipo = "WCHR"
                        },
                        new
                        {
                            ID = new Guid("7a86678b-64dd-4a5f-beac-13147a19de79"),
                            Tipo = "WCHS"
                        },
                        new
                        {
                            ID = new Guid("d4d989d1-4b43-477c-8fa8-f09b891f8618"),
                            Tipo = "WCHC"
                        },
                        new
                        {
                            ID = new Guid("57935f8b-8579-4a42-ae5e-2e62bbf169ca"),
                            Tipo = "BLIND"
                        },
                        new
                        {
                            ID = new Guid("458fff44-5ec2-45b1-8b5d-2510b641cc91"),
                            Tipo = "DEAF"
                        },
                        new
                        {
                            ID = new Guid("e01f774e-67e0-44a1-8671-8f90af915eb3"),
                            Tipo = "DPNA"
                        },
                        new
                        {
                            ID = new Guid("348ed92b-fc54-44cd-a760-817a41e22e1c"),
                            Tipo = "MAAS"
                        });
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.TipoMensagem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("ID");

                    b.ToTable("TiposMensagem");

                    b.HasData(
                        new
                        {
                            ID = new Guid("2ec46bc8-ba5f-42a4-bddf-abe9f783d7a7"),
                            Tipo = "PAL"
                        },
                        new
                        {
                            ID = new Guid("4742160c-7d2c-4215-b53e-8c10f97863ab"),
                            Tipo = "CAL"
                        },
                        new
                        {
                            ID = new Guid("b5fe799e-3c53-4276-9d27-c5c9bfb95dbe"),
                            Tipo = "PSM"
                        },
                        new
                        {
                            ID = new Guid("c283da42-5812-4cf3-ba2c-0cddae1edfa8"),
                            Tipo = "NET"
                        },
                        new
                        {
                            ID = new Guid("2c8fb881-51fd-4a55-a86c-dbad23b30551"),
                            Tipo = "AD-HOC"
                        });
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.TipoVoo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ID");

                    b.ToTable("TipoVoos");

                    b.HasData(
                        new
                        {
                            ID = new Guid("aaca62fc-8ad2-4a0a-a2ee-c1d94cd86700"),
                            Tipo = "ARR"
                        },
                        new
                        {
                            ID = new Guid("cd5d4ce2-f51e-4c93-a1ab-6b3e73688305"),
                            Tipo = "DEP"
                        });
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.Uh", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodAeroporto")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("NomeAeroporto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Uhs");

                    b.HasData(
                        new
                        {
                            ID = new Guid("807aeb52-f2d7-4152-8410-a668604a41d4"),
                            CodAeroporto = "AHD",
                            IATA = "LIS",
                            Nome = "LISBOA",
                            NomeAeroporto = "Aeroporto Humberto Delgado"
                        },
                        new
                        {
                            ID = new Guid("7a525467-1367-4ddf-9802-6bc44ae695ac"),
                            CodAeroporto = "ASC",
                            IATA = "OPO",
                            Nome = "PORTO",
                            NomeAeroporto = "Aeroporto Francisco Sá Carneiro"
                        },
                        new
                        {
                            ID = new Guid("7b277149-86d7-4c19-816c-0e97e803f491"),
                            CodAeroporto = "AFR",
                            IATA = "FAO",
                            Nome = "FARO",
                            NomeAeroporto = "Aeroporto de Faro"
                        },
                        new
                        {
                            ID = new Guid("7f6e20bd-7106-4c6f-a23d-dde9b0a1e471"),
                            CodAeroporto = "ACR",
                            IATA = "FNC",
                            Nome = "FUNCHAL",
                            NomeAeroporto = "Aeroporto Cristiano Ronaldo"
                        });
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.AppUserRole", b =>
                {
                    b.HasOne("MyWay2021.Server.Models.Identity.AppRole", "Role")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWay2021.Server.Models.Identity.AppUser", "User")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.UserUh", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Tabelas.Uh", "Uh")
                        .WithMany()
                        .HasForeignKey("UhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWay2021.Server.Models.Identity.AppUser", "User")
                        .WithMany("UserUhs")
                        .HasForeignKey("UserId1");

                    b.Navigation("Uh");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.Equipamento", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Relatorios.RelatorioDiario", "Relatorio")
                        .WithMany()
                        .HasForeignKey("RelatorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.Incumprimento", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Relatorios.RelatorioDiario", "Relatorio")
                        .WithMany()
                        .HasForeignKey("RelatorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.RelatorioDiario", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Tabelas.Uh", "Uh")
                        .WithMany()
                        .HasForeignKey("UhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uh");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.Sla", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Relatorios.RelatorioDiario", "Relatorio")
                        .WithMany()
                        .HasForeignKey("RelatorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.StaffOnDuty", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Tabelas.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWay2021.Shared.Models.Relatorios.RelatorioDiario", "Relatorio")
                        .WithMany()
                        .HasForeignKey("RelatorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Relatorios.TrabalhoSuplementar", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Tabelas.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWay2021.Shared.Models.Relatorios.RelatorioDiario", "Relatorio")
                        .WithMany()
                        .HasForeignKey("RelatorioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("MyWay2021.Shared.Models.Tabelas.Formando", b =>
                {
                    b.HasOne("MyWay2021.Shared.Models.Tabelas.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWay2021.Shared.Models.Tabelas.Uh", "Uh")
                        .WithMany()
                        .HasForeignKey("UhID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Uh");
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.AppRole", b =>
                {
                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("MyWay2021.Server.Models.Identity.AppUser", b =>
                {
                    b.Navigation("AppUserRoles");

                    b.Navigation("UserUhs");
                });
#pragma warning restore 612, 618
        }
    }
}
